services:
    server:
        build:
            context: .
            dockerfile: ./docker/apache/Dockerfile
        volumes:
            - ./:/var/www/html
            - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
        ports:
            - "8002:80"
        depends_on:
            - db
        networks:
            - simple-blog-network
        environment:
            XDEBUG_MODE: coverage

    db:
        image: mysql:latest
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "main"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - simple-blog-network

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - "8082:80"
        environment:
            PMA_HOST: "db"
            MYSQL_ROOT_PASSWORD: "root"
        depends_on:
            - db
        networks:
            - simple-blog-network

networks:
    simple-blog-network:
        driver: bridge

volumes:
    db_data:
        driver: local
